[View in Colaboratory](https://colab.research.google.com/github/buddharajuramaraju/DATA-ANALYSIS/blob/master/NumPy.ipynb)

# NumPy

## Introduction



1.   NumPy's main object is the homogeneous multidimensional array
2. It is a table of elements (usually numbers), all of the same type,indexed by a tuple of positive integers
3. In NumPy dimensions are called axes



## Example

In [3]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### ndarray.ndim
The number of axes(dimensions) of the array

In [4]:
a.ndim

2

### ndarray.shape
This is a tuple of integers indecating the size of array in each dimension

In [6]:
a.shape

(3, 5)

### ndarray.size
The total number of elements of the array, it is equal to the product of the elements of the shape

In [7]:
a.size

15

### ndarray.dtype
an object describing the type of elements of array, one can create or specify dtype's using standard python types. Aditionally numpy provides types of it's own

In [8]:
a.dtype

dtype('int64')

### ndarray.itemsize
The size in bytes of each elements of array

In [9]:
a.itemsize

8

### ndarray.data
The buffer containing the actual elements of the array


In [12]:
a.data

### type
Standard python function returns type of object

In [13]:
type(a)

numpy.ndarray

## NumPy Array Creation

There are several waays to create arrays

### From a regural Python List or Tuple

In [15]:
a = np.array([1,2,3])
a.dtype

dtype('int64')

In [18]:
b= np.array((1.0,2.34,5.6))
b.dtype

dtype('float64')

In [20]:
c= np.array([1,2,3,4],dtype=np.complex)
c

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [21]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
a = np.empty((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
a = np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [30]:
a = np.arange(0,3,0.2)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8])

In [33]:
a=np.linspace(0,3,10)
a

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [35]:
np.sin(a)

array([0.        , 0.3271947 , 0.6183698 , 0.84147098, 0.9719379 ,
       0.99540796, 0.90929743, 0.72308588, 0.45727263, 0.14112001])